/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentsPlatformStatus implements java.io.Serializable {

	private static final long serialVersionUID = 228351067;

	private java.lang.Integer                                                                           idexperimentsPlatformStatus;
	private edu.kit.ipd.crowdcontrol.objectservice.database.model.enums.ExperimentsPlatformStatusStatus status;
	private java.sql.Timestamp                                                                          timestamp;
	private java.lang.Integer                                                                           platform;

	public ExperimentsPlatformStatus() {}

	public ExperimentsPlatformStatus(
		java.lang.Integer                                                                           idexperimentsPlatformStatus,
		edu.kit.ipd.crowdcontrol.objectservice.database.model.enums.ExperimentsPlatformStatusStatus status,
		java.sql.Timestamp                                                                          timestamp,
		java.lang.Integer                                                                           platform
	) {
		this.idexperimentsPlatformStatus = idexperimentsPlatformStatus;
		this.status = status;
		this.timestamp = timestamp;
		this.platform = platform;
	}

	public java.lang.Integer getIdexperimentsPlatformStatus() {
		return this.idexperimentsPlatformStatus;
	}

	public void setIdexperimentsPlatformStatus(java.lang.Integer idexperimentsPlatformStatus) {
		this.idexperimentsPlatformStatus = idexperimentsPlatformStatus;
	}

	public edu.kit.ipd.crowdcontrol.objectservice.database.model.enums.ExperimentsPlatformStatusStatus getStatus() {
		return this.status;
	}

	public void setStatus(edu.kit.ipd.crowdcontrol.objectservice.database.model.enums.ExperimentsPlatformStatusStatus status) {
		this.status = status;
	}

	public java.sql.Timestamp getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(java.sql.Timestamp timestamp) {
		this.timestamp = timestamp;
	}

	public java.lang.Integer getPlatform() {
		return this.platform;
	}

	public void setPlatform(java.lang.Integer platform) {
		this.platform = platform;
	}
}
