/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task implements java.io.Serializable {

	private static final long serialVersionUID = 622268417;

	private java.lang.Integer                                                       idTask;
	private java.lang.Integer                                                       experimentPlatform;
	private java.lang.String                                                        platformData;
	private edu.kit.ipd.crowdcontrol.objectservice.database.model.enums.TaskStopgap stopgap;

	public Task() {}

	public Task(
		java.lang.Integer                                                       idTask,
		java.lang.Integer                                                       experimentPlatform,
		java.lang.String                                                        platformData,
		edu.kit.ipd.crowdcontrol.objectservice.database.model.enums.TaskStopgap stopgap
	) {
		this.idTask = idTask;
		this.experimentPlatform = experimentPlatform;
		this.platformData = platformData;
		this.stopgap = stopgap;
	}

	public java.lang.Integer getIdTask() {
		return this.idTask;
	}

	public void setIdTask(java.lang.Integer idTask) {
		this.idTask = idTask;
	}

	public java.lang.Integer getExperimentPlatform() {
		return this.experimentPlatform;
	}

	public void setExperimentPlatform(java.lang.Integer experimentPlatform) {
		this.experimentPlatform = experimentPlatform;
	}

	public java.lang.String getPlatformData() {
		return this.platformData;
	}

	public void setPlatformData(java.lang.String platformData) {
		this.platformData = platformData;
	}

	public edu.kit.ipd.crowdcontrol.objectservice.database.model.enums.TaskStopgap getStopgap() {
		return this.stopgap;
	}

	public void setStopgap(edu.kit.ipd.crowdcontrol.objectservice.database.model.enums.TaskStopgap stopgap) {
		this.stopgap = stopgap;
	}
}
