/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crowdcontrolproto extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1729106863;

	/**
	 * The singleton instance of <code>crowdcontrolproto</code>
	 */
	public static final Crowdcontrolproto CROWDCONTROLPROTO = new Crowdcontrolproto();

	/**
	 * No further instances allowed
	 */
	private Crowdcontrolproto() {
		super("crowdcontrolproto");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Answers.ANSWERS,
			edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment.EXPERIMENT,
			edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Hit.HIT,
			edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS,
			edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratings.RATINGS,
			edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags.TAGS);
	}
}
