/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>crowdcontrolproto</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.ExperimentRecord> KEY_EXPERIMENT_PRIMARY = UniqueKeys0.KEY_EXPERIMENT_PRIMARY;
	public static final org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.ExperimentRecord> KEY_EXPERIMENT_ID_UNIQUE = UniqueKeys0.KEY_EXPERIMENT_ID_UNIQUE;
	public static final org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord> KEY_RATINGOPTIONS_PRIMARY = UniqueKeys0.KEY_RATINGOPTIONS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.ExperimentRecord> KEY_EXPERIMENT_PRIMARY = createUniqueKey(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment.EXPERIMENT, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment.EXPERIMENT.ID);
		public static final org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.ExperimentRecord> KEY_EXPERIMENT_ID_UNIQUE = createUniqueKey(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment.EXPERIMENT, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment.EXPERIMENT.ID);
		public static final org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord> KEY_RATINGOPTIONS_PRIMARY = createUniqueKey(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions.RATINGOPTIONS, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions.RATINGOPTIONS.IDRATINGOPTIONS);
	}
}
