/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in crowdcontrolproto
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table crowdcontrolproto.Answers
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Answers ANSWERS = edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Answers.ANSWERS;

	/**
	 * The table crowdcontrolproto.Experiment
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment EXPERIMENT = edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment.EXPERIMENT;

	/**
	 * The table crowdcontrolproto.HIT
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Hit HIT = edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Hit.HIT;

	/**
	 * The table crowdcontrolproto.Qualifications
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications QUALIFICATIONS = edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS;

	/**
	 * The table crowdcontrolproto.Ratings
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratings RATINGS = edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratings.RATINGS;

	/**
	 * The table crowdcontrolproto.Tags
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags TAGS = edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags.TAGS;
}
