/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in crowdcontrolproto
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table crowdcontrolproto.experiment
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment EXPERIMENT = edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Experiment.EXPERIMENT;

	/**
	 * The table crowdcontrolproto.RatingOptions
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions RATINGOPTIONS = edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions.RATINGOPTIONS;
}
