-- MySQL Script generated by MySQL Workbench
-- Wed Jan 13 16:57:39 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crowdcontrol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crowdcontrol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crowdcontrol` DEFAULT CHARACTER SET utf8mb4 ;
USE `crowdcontrol` ;

-- -----------------------------------------------------
-- Table `crowdcontrol`.`Template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Template` (
  `idTemplate` INT NOT NULL,
  `template` LONGTEXT NOT NULL,
  `titel` VARCHAR(255) NULL,
  `answer_type` VARCHAR(45) NULL,
  PRIMARY KEY (`idTemplate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Experiment` (
  `idexperiment` INT(11) NOT NULL,
  `rating_options` JSON NULL DEFAULT NULL,
  `titel` VARCHAR(255) NULL DEFAULT NULL,
  `answer_description` TEXT NULL DEFAULT NULL,
  `ratings_per_answer` INT(11) NULL DEFAULT NULL,
  `algorithm_task_chooser` VARCHAR(255) NULL DEFAULT NULL,
  `algorithm_quality_answer` VARCHAR(255) NULL DEFAULT NULL,
  `algorithm_quality_rating` VARCHAR(255) NULL DEFAULT NULL,
  `base_payment` INT(11) NULL DEFAULT NULL,
  `bonus_answer` INT(11) NULL DEFAULT NULL,
  `bonus_rating` INT(11) NULL DEFAULT NULL,
  `template_data` MEDIUMTEXT NULL DEFAULT NULL,
  `template` INT NULL,
  `answer_type` VARCHAR(45) NULL,
  PRIMARY KEY (`idexperiment`),
  INDEX `usedTemplate_idx` (`template` ASC),
  CONSTRAINT `usedTemplate`
    FOREIGN KEY (`template`)
    REFERENCES `crowdcontrol`.`Template` (`idTemplate`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Platform` (
  `idPlatform` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `render_calibrations` BIT(1) NOT NULL,
  `needs_email` BIT(1) NOT NULL,
  PRIMARY KEY (`idPlatform`),
  UNIQUE INDEX `idPlatform_UNIQUE` (`idPlatform` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Task` (
  `idTask` INT(11) NOT NULL,
  `experiment` INT(11) NOT NULL,
  `running` BIT(1) NOT NULL,
  `platform_data` MEDIUMTEXT NULL DEFAULT NULL,
  `crowd_platform` VARCHAR(255) NOT NULL,
  `stopping` BIT(1) NOT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `idexperiment_idx` (`experiment` ASC),
  INDEX `runningOnPlattform_idx` (`crowd_platform` ASC),
  CONSTRAINT `idexperimenthit`
    FOREIGN KEY (`experiment`)
    REFERENCES `crowdcontrol`.`Experiment` (`idexperiment`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `runningOnPlattform`
    FOREIGN KEY (`crowd_platform`)
    REFERENCES `crowdcontrol`.`Platform` (`idPlatform`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Worker` (
  `idWorker` INT(11) NOT NULL,
  `identification` VARCHAR(255) NULL DEFAULT NULL,
  `platform` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`idWorker`),
  INDEX `workerOrigin_idx` (`platform` ASC),
  CONSTRAINT `workerOrigin`
    FOREIGN KEY (`platform`)
    REFERENCES `crowdcontrol`.`Platform` (`idPlatform`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Answer` (
  `idAnswer` INT(11) NOT NULL,
  `task` INT(11) NOT NULL,
  `answer` MEDIUMTEXT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `worker_id` INT(11) NOT NULL,
  `quality` INT NULL,
  PRIMARY KEY (`idAnswer`),
  INDEX `workerAnswered_idx` (`worker_id` ASC),
  INDEX `idHITanswers_idx` (`task` ASC),
  CONSTRAINT `idHITanswers`
    FOREIGN KEY (`task`)
    REFERENCES `crowdcontrol`.`Task` (`idTask`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `workerAnswered`
    FOREIGN KEY (`worker_id`)
    REFERENCES `crowdcontrol`.`Worker` (`idWorker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Constraint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Constraint` (
  `idConstraint` INT(11) NOT NULL,
  `constraint` VARCHAR(45) NOT NULL,
  `experiment` INT(11) NOT NULL,
  PRIMARY KEY (`idConstraint`),
  INDEX `constrainedExperiment` (`experiment` ASC),
  CONSTRAINT `constrainedExperiment`
    FOREIGN KEY (`experiment`)
    REFERENCES `crowdcontrol`.`Experiment` (`idexperiment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`GiftCode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`GiftCode` (
  `idGiftCode` INT NOT NULL,
  `code` MEDIUMTEXT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`idGiftCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Payment` (
  `idPayment` INT(11) NOT NULL,
  `worker_id` INT(11) NOT NULL,
  `experiment_id` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` INT NOT NULL,
  `giftcode` INT NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `payedWorker_idx` (`worker_id` ASC),
  INDEX `payedExperiment_idx` (`experiment_id` ASC),
  INDEX `usedGiftCode_idx` (`giftcode` ASC),
  CONSTRAINT `payedExperiment`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `crowdcontrol`.`Experiment` (`idexperiment`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `payedWorker`
    FOREIGN KEY (`worker_id`)
    REFERENCES `crowdcontrol`.`Worker` (`idWorker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `usedGiftCode`
    FOREIGN KEY (`giftcode`)
    REFERENCES `crowdcontrol`.`GiftCode` (`idGiftCode`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Population`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Population` (
  `idPopulation` INT(11) NOT NULL,
  `property` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `name` VARCHAR(255) NOT NULL,
  `experiment` INT NULL,
  PRIMARY KEY (`idPopulation`),
  UNIQUE INDEX `experiment_UNIQUE` (`experiment` ASC),
  CONSTRAINT `participatedIn`
    FOREIGN KEY (`experiment`)
    REFERENCES `crowdcontrol`.`Experiment` (`idexperiment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Rating` (
  `idRating` INT(11) NOT NULL,
  `task` INT(11) NOT NULL,
  `answer_r` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rating` INT(11) NULL DEFAULT NULL,
  `worker_id` INT(11) NOT NULL,
  `quality` INT NULL,
  PRIMARY KEY (`idRating`),
  INDEX `idAnswers_idx` (`answer_r` ASC),
  INDEX `workerRated_idx` (`worker_id` ASC),
  INDEX `idHITrating_idx` (`task` ASC),
  CONSTRAINT `idAnswersratins`
    FOREIGN KEY (`answer_r`)
    REFERENCES `crowdcontrol`.`Answer` (`idAnswer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idHITrating`
    FOREIGN KEY (`task`)
    REFERENCES `crowdcontrol`.`Task` (`idTask`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `workerRated`
    FOREIGN KEY (`worker_id`)
    REFERENCES `crowdcontrol`.`Worker` (`idWorker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Tag` (
  `idTag` INT(11) NOT NULL,
  `tag` VARCHAR(255) NOT NULL,
  `experiment` INT(11) NOT NULL,
  PRIMARY KEY (`idTag`),
  INDEX `idexperiment_idx` (`experiment` ASC),
  CONSTRAINT `idexperimenttags`
    FOREIGN KEY (`experiment`)
    REFERENCES `crowdcontrol`.`Experiment` (`idexperiment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`PopulationAnswerOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`PopulationAnswerOption` (
  `idPopulationAnswerOption` INT NOT NULL,
  `population` INT NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPopulationAnswerOption`),
  INDEX `populationAnswer_idx` (`population` ASC),
  CONSTRAINT `populationAnswer`
    FOREIGN KEY (`population`)
    REFERENCES `crowdcontrol`.`Population` (`idPopulation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`ExperimentsPopulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`ExperimentsPopulation` (
  `idExperimentsPopulation` VARCHAR(255) NOT NULL,
  `population_user` INT NOT NULL,
  `answer` INT NOT NULL,
  `referenced_platform` VARCHAR(255) NOT NULL,
  `not` BIT(1) NOT NULL,
  PRIMARY KEY (`idExperimentsPopulation`),
  INDEX `populationUser_idx` (`population_user` ASC),
  INDEX `referencedPlatform_idx` (`referenced_platform` ASC),
  INDEX `referencedAnswer_idx` (`answer` ASC),
  CONSTRAINT `populationUser`
    FOREIGN KEY (`population_user`)
    REFERENCES `crowdcontrol`.`Experiment` (`idexperiment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `referencedPlatform`
    FOREIGN KEY (`referenced_platform`)
    REFERENCES `crowdcontrol`.`Platform` (`idPlatform`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `referencedAnswer`
    FOREIGN KEY (`answer`)
    REFERENCES `crowdcontrol`.`PopulationAnswerOption` (`idPopulationAnswerOption`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`PopulationResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`PopulationResult` (
  `idPopulationResult` INT NOT NULL,
  `worker` INT NOT NULL,
  `answer` INT NOT NULL,
  PRIMARY KEY (`idPopulationResult`),
  INDEX `referencedAnswer_idx` (`answer` ASC),
  INDEX `referencedWorker_idx` (`worker` ASC),
  CONSTRAINT `chosenAnswer`
    FOREIGN KEY (`answer`)
    REFERENCES `crowdcontrol`.`PopulationAnswerOption` (`idPopulationAnswerOption`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `referencedWorker`
    FOREIGN KEY (`worker`)
    REFERENCES `crowdcontrol`.`Worker` (`idWorker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowdcontrol`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdcontrol`.`Notification` (
  `idNotification` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `checkPeriod` INT NOT NULL,
  `sendThreshold` INT NOT NULL,
  `query` MEDIUMTEXT NOT NULL,
  `lastSent` TIMESTAMP NULL,
  PRIMARY KEY (`idNotification`))
ENGINE = InnoDB;

USE `crowdcontrol`;

DELIMITER $$
USE `crowdcontrol`$$
CREATE DEFINER = CURRENT_USER TRIGGER `crowdcontrol`.`Platform_BEFORE_INSERT` BEFORE INSERT ON `Platform` FOR EACH ROW
BEGIN
	IF REGEXP_LIKE (NEW.idPlatform, '[a-z0-9._-]+') THEN
		SET NEW.idPlatform = LOWER(NEW.idPlatform);
	ELSE
		SET NEW.idPlatform = NULL;
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
