/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experimentspopulation implements java.io.Serializable {

	private static final long serialVersionUID = -519867547;

	private java.lang.String  idexperimentspopulation;
	private java.lang.Integer populationUser;
	private java.lang.Integer correctAnswer;
	private java.lang.String  referencedPlatform;
	private java.lang.Boolean not;

	public Experimentspopulation() {}

	public Experimentspopulation(
		java.lang.String  idexperimentspopulation,
		java.lang.Integer populationUser,
		java.lang.Integer correctAnswer,
		java.lang.String  referencedPlatform,
		java.lang.Boolean not
	) {
		this.idexperimentspopulation = idexperimentspopulation;
		this.populationUser = populationUser;
		this.correctAnswer = correctAnswer;
		this.referencedPlatform = referencedPlatform;
		this.not = not;
	}

	public java.lang.String getIdexperimentspopulation() {
		return this.idexperimentspopulation;
	}

	public void setIdexperimentspopulation(java.lang.String idexperimentspopulation) {
		this.idexperimentspopulation = idexperimentspopulation;
	}

	public java.lang.Integer getPopulationUser() {
		return this.populationUser;
	}

	public void setPopulationUser(java.lang.Integer populationUser) {
		this.populationUser = populationUser;
	}

	public java.lang.Integer getCorrectAnswer() {
		return this.correctAnswer;
	}

	public void setCorrectAnswer(java.lang.Integer correctAnswer) {
		this.correctAnswer = correctAnswer;
	}

	public java.lang.String getReferencedPlatform() {
		return this.referencedPlatform;
	}

	public void setReferencedPlatform(java.lang.String referencedPlatform) {
		this.referencedPlatform = referencedPlatform;
	}

	public java.lang.Boolean getNot() {
		return this.not;
	}

	public void setNot(java.lang.Boolean not) {
		this.not = not;
	}
}
