/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pictures implements java.io.Serializable {

	private static final long serialVersionUID = -1441181327;

	private java.lang.Integer idpictures;
	private java.lang.Integer experiment;
	private java.lang.String  pictureUrl;
	private java.lang.String  pictureLicenseUr;

	public Pictures() {}

	public Pictures(
		java.lang.Integer idpictures,
		java.lang.Integer experiment,
		java.lang.String  pictureUrl,
		java.lang.String  pictureLicenseUr
	) {
		this.idpictures = idpictures;
		this.experiment = experiment;
		this.pictureUrl = pictureUrl;
		this.pictureLicenseUr = pictureLicenseUr;
	}

	public java.lang.Integer getIdpictures() {
		return this.idpictures;
	}

	public void setIdpictures(java.lang.Integer idpictures) {
		this.idpictures = idpictures;
	}

	public java.lang.Integer getExperiment() {
		return this.experiment;
	}

	public void setExperiment(java.lang.Integer experiment) {
		this.experiment = experiment;
	}

	public java.lang.String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(java.lang.String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public java.lang.String getPictureLicenseUr() {
		return this.pictureLicenseUr;
	}

	public void setPictureLicenseUr(java.lang.String pictureLicenseUr) {
		this.pictureLicenseUr = pictureLicenseUr;
	}
}
