/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Worker implements java.io.Serializable {

	private static final long serialVersionUID = -1032201546;

	private java.lang.Integer idworker;
	private java.lang.Object  platformData;

	public Worker() {}

	public Worker(
		java.lang.Integer idworker,
		java.lang.Object  platformData
	) {
		this.idworker = idworker;
		this.platformData = platformData;
	}

	public java.lang.Integer getIdworker() {
		return this.idworker;
	}

	public void setIdworker(java.lang.Integer idworker) {
		this.idworker = idworker;
	}

	public java.lang.Object getPlatformData() {
		return this.platformData;
	}

	public void setPlatformData(java.lang.Object platformData) {
		this.platformData = platformData;
	}
}
