/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QualificationsRecord extends org.jooq.impl.UpdatableRecordImpl<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1155806445;

	/**
	 * Setter for <code>crowdcontrolproto.Qualifications.idQualifications</code>.
	 */
	public void setIdqualifications(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrolproto.Qualifications.idQualifications</code>.
	 */
	public java.lang.Integer getIdqualifications() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrolproto.Qualifications.text</code>.
	 */
	public void setText(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrolproto.Qualifications.text</code>.
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>crowdcontrolproto.Qualifications.experiment_q</code>.
	 */
	public void setExperimentQ(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crowdcontrolproto.Qualifications.experiment_q</code>.
	 */
	public java.lang.Integer getExperimentQ() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS.IDQUALIFICATIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS.EXPERIMENT_Q;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdqualifications();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getExperimentQ();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QualificationsRecord value1(java.lang.Integer value) {
		setIdqualifications(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QualificationsRecord value2(java.lang.String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QualificationsRecord value3(java.lang.Integer value) {
		setExperimentQ(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QualificationsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QualificationsRecord
	 */
	public QualificationsRecord() {
		super(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS);
	}

	/**
	 * Create a detached, initialised QualificationsRecord
	 */
	public QualificationsRecord(java.lang.Integer idqualifications, java.lang.String text, java.lang.Integer experimentQ) {
		super(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS);

		setValue(0, idqualifications);
		setValue(1, text);
		setValue(2, experimentQ);
	}
}
