// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algorithm_list.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public interface AlgorithmListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.AlgorithmList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .crowdcontrol.AlgorithmOption items = 1;</code>
   */
  java.util.List<edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOption> 
      getItemsList();
  /**
   * <code>repeated .crowdcontrol.AlgorithmOption items = 1;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOption getItems(int index);
  /**
   * <code>repeated .crowdcontrol.AlgorithmOption items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .crowdcontrol.AlgorithmOption items = 1;</code>
   */
  java.util.List<? extends edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOptionOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .crowdcontrol.AlgorithmOption items = 1;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOptionOrBuilder getItemsOrBuilder(
      int index);
}
