// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calibration_answer.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public interface CalibrationAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.CalibrationAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 worker_id = 1;</code>
   */
  int getWorkerId();

  /**
   * <code>optional int32 answer_id = 2;</code>
   */
  int getAnswerId();
}
