// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: experiment.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public final class ExperimentOuterClass {
  private ExperimentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_crowdcontrol_Experiment_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crowdcontrol_Experiment_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_crowdcontrol_Experiment_PlaceholdersEntry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crowdcontrol_Experiment_PlaceholdersEntry_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_crowdcontrol_Experiment_PlatformPopulation_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crowdcontrol_Experiment_PlatformPopulation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020experiment.proto\022\014crowdcontrol\032\021answer" +
      "_type.proto\032\020constraint.proto\032\020populatio" +
      "n.proto\032\ttag.proto\"\246\007\n\nExperiment\022\n\n\002id\030" +
      "\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\023\n\013description\030\003 \001(" +
      "\t\022-\n\005state\030\004 \001(\0162\036.crowdcontrol.Experime" +
      "nt.State\022-\n\013answer_type\030\005 \001(\0162\030.crowdcon" +
      "trol.AnswerType\022\036\n\026algorithm_task_choose" +
      "r\030\006 \001(\t\022 \n\030algorithm_quality_answer\030\007 \001(" +
      "\t\022 \n\030algorithm_quality_rating\030\010 \001(\t\022\032\n\022a" +
      "nswers_per_worker\030\t \001(\005\022\032\n\022ratings_per_w",
      "orker\030\n \001(\005\022\032\n\022ratings_per_answer\030\013 \001(\005\022" +
      "\026\n\016needed_answers\030\014 \001(\005\022\024\n\014payment_base\030" +
      "\r \001(\005\022\026\n\016payment_answer\030\016 \001(\005\022\026\n\016payment" +
      "_rating\030\017 \001(\005\022-\n\013constraints\030\020 \003(\0132\030.cro" +
      "wdcontrol.Constraint\022\037\n\004tags\030\021 \003(\0132\021.cro" +
      "wdcontrol.Tag\022I\n\024platform_populations\030\022 " +
      "\003(\0132+.crowdcontrol.Experiment.PlatformPo" +
      "pulation\022@\n\014placeholders\030\023 \003(\0132*.crowdco" +
      "ntrol.Experiment.PlaceholdersEntry\022 \n\030wo" +
      "rker_quality_threshold\030\024 \001(\005\022\023\n\013template",
      "_id\030\025 \001(\005\0323\n\021PlaceholdersEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032X\n\022PlatformPopula" +
      "tion\022\023\n\013platform_id\030\001 \001(\t\022-\n\013populations" +
      "\030\002 \003(\0132\030.crowdcontrol.Population\"Q\n\005Stat" +
      "e\022\013\n\007INVALID\020\000\022\t\n\005DRAFT\020\001\022\r\n\tPUBLISHED\020\002" +
      "\022\024\n\020CREATIVE_STOPPED\020\003\022\013\n\007STOPPED\020\004B0\n,e" +
      "du.kit.ipd.crowdcontrol.objectservice.pr" +
      "otoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.kit.ipd.crowdcontrol.objectservice.proto.AnswerTypeOuterClass.getDescriptor(),
          edu.kit.ipd.crowdcontrol.objectservice.proto.ConstraintOuterClass.getDescriptor(),
          edu.kit.ipd.crowdcontrol.objectservice.proto.PopulationOuterClass.getDescriptor(),
          edu.kit.ipd.crowdcontrol.objectservice.proto.TagOuterClass.getDescriptor(),
        }, assigner);
    internal_static_crowdcontrol_Experiment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crowdcontrol_Experiment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crowdcontrol_Experiment_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "State", "AnswerType", "AlgorithmTaskChooser", "AlgorithmQualityAnswer", "AlgorithmQualityRating", "AnswersPerWorker", "RatingsPerWorker", "RatingsPerAnswer", "NeededAnswers", "PaymentBase", "PaymentAnswer", "PaymentRating", "Constraints", "Tags", "PlatformPopulations", "Placeholders", "WorkerQualityThreshold", "TemplateId", });
    internal_static_crowdcontrol_Experiment_PlaceholdersEntry_descriptor =
      internal_static_crowdcontrol_Experiment_descriptor.getNestedTypes().get(0);
    internal_static_crowdcontrol_Experiment_PlaceholdersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crowdcontrol_Experiment_PlaceholdersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_crowdcontrol_Experiment_PlatformPopulation_descriptor =
      internal_static_crowdcontrol_Experiment_descriptor.getNestedTypes().get(1);
    internal_static_crowdcontrol_Experiment_PlatformPopulation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crowdcontrol_Experiment_PlatformPopulation_descriptor,
        new java.lang.String[] { "PlatformId", "Populations", });
    edu.kit.ipd.crowdcontrol.objectservice.proto.AnswerTypeOuterClass.getDescriptor();
    edu.kit.ipd.crowdcontrol.objectservice.proto.ConstraintOuterClass.getDescriptor();
    edu.kit.ipd.crowdcontrol.objectservice.proto.PopulationOuterClass.getDescriptor();
    edu.kit.ipd.crowdcontrol.objectservice.proto.TagOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
