// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public final class NotificationOuterClass {
  private NotificationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_crowdcontrol_Notification_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crowdcontrol_Notification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022notification.proto\022\014crowdcontrol\"\205\001\n\014N" +
      "otification\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\023\n" +
      "\013description\030\003 \001(\t\022\r\n\005query\030\004 \001(\t\022\024\n\014che" +
      "ck_period\030\005 \001(\005\022\021\n\tsend_once\030\006 \001(\010\022\016\n\006em" +
      "ails\030\007 \003(\tB0\n,edu.kit.ipd.crowdcontrol.o" +
      "bjectservice.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_crowdcontrol_Notification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crowdcontrol_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crowdcontrol_Notification_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Query", "CheckPeriod", "SendOnce", "Emails", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
