/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.objectservice.database.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in crowdcontrol
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table crowdcontrol.Answers
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Answers ANSWERS = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Answers.ANSWERS;

	/**
	 * The table crowdcontrol.Experiment
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Experiment EXPERIMENT = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Experiment.EXPERIMENT;

	/**
	 * The table crowdcontrol.HIT
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Hit HIT = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Hit.HIT;

	/**
	 * The table crowdcontrol.Payment
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Payment PAYMENT = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Payment.PAYMENT;

	/**
	 * The table crowdcontrol.Pictures
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Pictures PICTURES = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Pictures.PICTURES;

	/**
	 * The table crowdcontrol.Population
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Population POPULATION = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Population.POPULATION;

	/**
	 * The table crowdcontrol.Ratings
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Ratings RATINGS = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Ratings.RATINGS;

	/**
	 * The table crowdcontrol.Tags
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Tags TAGS = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Tags.TAGS;

	/**
	 * The table crowdcontrol.Worker
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Worker WORKER = edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Worker.WORKER;
}
