/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PicturesDao extends org.jooq.impl.DAOImpl<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord, edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures, java.lang.Integer> {

	/**
	 * Create a new PicturesDao without any configuration
	 */
	public PicturesDao() {
		super(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures.PICTURES, edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures.class);
	}

	/**
	 * Create a new PicturesDao with an attached configuration
	 */
	public PicturesDao(org.jooq.Configuration configuration) {
		super(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures.PICTURES, edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures object) {
		return object.getIdpictures();
	}

	/**
	 * Fetch records that have <code>idPictures IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures> fetchByIdpictures(java.lang.Integer... values) {
		return fetch(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures.PICTURES.IDPICTURES, values);
	}

	/**
	 * Fetch a unique record that has <code>idPictures = value</code>
	 */
	public edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures fetchOneByIdpictures(java.lang.Integer value) {
		return fetchOne(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures.PICTURES.IDPICTURES, value);
	}

	/**
	 * Fetch records that have <code>experiment IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures> fetchByExperiment(java.lang.Integer... values) {
		return fetch(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures.PICTURES.EXPERIMENT, values);
	}

	/**
	 * Fetch records that have <code>picture_url IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures> fetchByPictureUrl(java.lang.String... values) {
		return fetch(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures.PICTURES.PICTURE_URL, values);
	}

	/**
	 * Fetch records that have <code>picture_license_ur IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.pojos.Pictures> fetchByPictureLicenseUr(java.lang.String... values) {
		return fetch(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures.PICTURES.PICTURE_LICENSE_UR, values);
	}
}
