/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingConstraintsDao extends org.jooq.impl.DAOImpl<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord, edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos.RatingConstraints, java.lang.Integer> {

	/**
	 * Create a new RatingConstraintsDao without any configuration
	 */
	public RatingConstraintsDao() {
		super(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS, edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos.RatingConstraints.class);
	}

	/**
	 * Create a new RatingConstraintsDao with an attached configuration
	 */
	public RatingConstraintsDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS, edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos.RatingConstraints.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos.RatingConstraints object) {
		return object.getIdRatingConstraints();
	}

	/**
	 * Fetch records that have <code>id_rating_Constraints IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos.RatingConstraints> fetchByIdRatingConstraints(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS.ID_RATING_CONSTRAINTS, values);
	}

	/**
	 * Fetch a unique record that has <code>id_rating_Constraints = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos.RatingConstraints fetchOneByIdRatingConstraints(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS.ID_RATING_CONSTRAINTS, value);
	}

	/**
	 * Fetch records that have <code>ref_rating IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos.RatingConstraints> fetchByRefRating(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS.REF_RATING, values);
	}

	/**
	 * Fetch records that have <code>off_constraint IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.pojos.RatingConstraints> fetchByOffConstraint(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS.OFF_CONSTRAINT, values);
	}
}
