/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingConstraintsRecord extends org.jooq.impl.UpdatableRecordImpl<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1861850806;

	/**
	 * Setter for <code>crowdcontrol.Rating_Constraints.id_rating_Constraints</code>.
	 */
	public void setIdRatingConstraints(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Rating_Constraints.id_rating_Constraints</code>.
	 */
	public java.lang.Integer getIdRatingConstraints() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrol.Rating_Constraints.ref_rating</code>.
	 */
	public void setRefRating(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Rating_Constraints.ref_rating</code>.
	 */
	public java.lang.Integer getRefRating() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>crowdcontrol.Rating_Constraints.off_constraint</code>.
	 */
	public void setOffConstraint(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Rating_Constraints.off_constraint</code>.
	 */
	public java.lang.Integer getOffConstraint() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS.ID_RATING_CONSTRAINTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS.REF_RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS.OFF_CONSTRAINT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdRatingConstraints();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRefRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getOffConstraint();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingConstraintsRecord value1(java.lang.Integer value) {
		setIdRatingConstraints(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingConstraintsRecord value2(java.lang.Integer value) {
		setRefRating(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingConstraintsRecord value3(java.lang.Integer value) {
		setOffConstraint(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingConstraintsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RatingConstraintsRecord
	 */
	public RatingConstraintsRecord() {
		super(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS);
	}

	/**
	 * Create a detached, initialised RatingConstraintsRecord
	 */
	public RatingConstraintsRecord(java.lang.Integer idRatingConstraints, java.lang.Integer refRating, java.lang.Integer offConstraint) {
		super(edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS);

		setValue(0, idRatingConstraints);
		setValue(1, refRating);
		setValue(2, offConstraint);
	}
}
