/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Answers implements java.io.Serializable {

	private static final long serialVersionUID = -1196223637;

	private java.lang.Integer  idanswers;
	private java.lang.Integer  hitA;
	private java.lang.String   answer;
	private java.sql.Timestamp timestamp;
	private java.lang.String   workerid;

	public Answers() {}

	public Answers(
		java.lang.Integer  idanswers,
		java.lang.Integer  hitA,
		java.lang.String   answer,
		java.sql.Timestamp timestamp,
		java.lang.String   workerid
	) {
		this.idanswers = idanswers;
		this.hitA = hitA;
		this.answer = answer;
		this.timestamp = timestamp;
		this.workerid = workerid;
	}

	public java.lang.Integer getIdanswers() {
		return this.idanswers;
	}

	public void setIdanswers(java.lang.Integer idanswers) {
		this.idanswers = idanswers;
	}

	public java.lang.Integer getHitA() {
		return this.hitA;
	}

	public void setHitA(java.lang.Integer hitA) {
		this.hitA = hitA;
	}

	public java.lang.String getAnswer() {
		return this.answer;
	}

	public void setAnswer(java.lang.String answer) {
		this.answer = answer;
	}

	public java.sql.Timestamp getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(java.sql.Timestamp timestamp) {
		this.timestamp = timestamp;
	}

	public java.lang.String getWorkerid() {
		return this.workerid;
	}

	public void setWorkerid(java.lang.String workerid) {
		this.workerid = workerid;
	}
}
