/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Qualifications implements java.io.Serializable {

	private static final long serialVersionUID = 237195448;

	private java.lang.Integer idqualifications;
	private java.lang.String  text;
	private java.lang.Integer experimentQ;

	public Qualifications() {}

	public Qualifications(
		java.lang.Integer idqualifications,
		java.lang.String  text,
		java.lang.Integer experimentQ
	) {
		this.idqualifications = idqualifications;
		this.text = text;
		this.experimentQ = experimentQ;
	}

	public java.lang.Integer getIdqualifications() {
		return this.idqualifications;
	}

	public void setIdqualifications(java.lang.Integer idqualifications) {
		this.idqualifications = idqualifications;
	}

	public java.lang.String getText() {
		return this.text;
	}

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.Integer getExperimentQ() {
		return this.experimentQ;
	}

	public void setExperimentQ(java.lang.Integer experimentQ) {
		this.experimentQ = experimentQ;
	}
}
