/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PicturesRecord extends org.jooq.impl.UpdatableRecordImpl<edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.records.PicturesRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1411564570;

	/**
	 * Setter for <code>crowdcontrol.Pictures.idPictures</code>.
	 */
	public void setIdpictures(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Pictures.idPictures</code>.
	 */
	public java.lang.Integer getIdpictures() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrol.Pictures.experiment</code>.
	 */
	public void setExperiment(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Pictures.experiment</code>.
	 */
	public java.lang.Integer getExperiment() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>crowdcontrol.Pictures.picture_url</code>.
	 */
	public void setPictureUrl(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Pictures.picture_url</code>.
	 */
	public java.lang.String getPictureUrl() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>crowdcontrol.Pictures.picture_license_ur</code>.
	 */
	public void setPictureLicenseUr(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Pictures.picture_license_ur</code>.
	 */
	public java.lang.String getPictureLicenseUr() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Pictures.PICTURES.IDPICTURES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Pictures.PICTURES.EXPERIMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Pictures.PICTURES.PICTURE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Pictures.PICTURES.PICTURE_LICENSE_UR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdpictures();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getExperiment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPictureUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPictureLicenseUr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicturesRecord value1(java.lang.Integer value) {
		setIdpictures(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicturesRecord value2(java.lang.Integer value) {
		setExperiment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicturesRecord value3(java.lang.String value) {
		setPictureUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicturesRecord value4(java.lang.String value) {
		setPictureLicenseUr(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicturesRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PicturesRecord
	 */
	public PicturesRecord() {
		super(edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Pictures.PICTURES);
	}

	/**
	 * Create a detached, initialised PicturesRecord
	 */
	public PicturesRecord(java.lang.Integer idpictures, java.lang.Integer experiment, java.lang.String pictureUrl, java.lang.String pictureLicenseUr) {
		super(edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Pictures.PICTURES);

		setValue(0, idpictures);
		setValue(1, experiment);
		setValue(2, pictureUrl);
		setValue(3, pictureLicenseUr);
	}
}
