/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerRecord extends org.jooq.impl.UpdatableRecordImpl<edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.records.WorkerRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Object> {

	private static final long serialVersionUID = 1733919581;

	/**
	 * Setter for <code>crowdcontrol.Worker.idWorker</code>.
	 */
	public void setIdworker(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker.idWorker</code>.
	 */
	public java.lang.Integer getIdworker() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrol.Worker.platform_data</code>.
	 */
	public void setPlatformData(java.lang.Object value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker.platform_data</code>.
	 */
	public java.lang.Object getPlatformData() {
		return (java.lang.Object) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Object> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Object> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Worker.WORKER.IDWORKER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field2() {
		return edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Worker.WORKER.PLATFORM_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdworker();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value2() {
		return getPlatformData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerRecord value1(java.lang.Integer value) {
		setIdworker(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerRecord value2(java.lang.Object value) {
		setPlatformData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerRecord values(java.lang.Integer value1, java.lang.Object value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WorkerRecord
	 */
	public WorkerRecord() {
		super(edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Worker.WORKER);
	}

	/**
	 * Create a detached, initialised WorkerRecord
	 */
	public WorkerRecord(java.lang.Integer idworker, java.lang.Object platformData) {
		super(edu.ipd.kit.crowdcontrol.objectservice.database.model.tables.Worker.WORKER);

		setValue(0, idworker);
		setValue(1, platformData);
	}
}
