/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Qualifications extends org.jooq.impl.TableImpl<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord> {

	private static final long serialVersionUID = 311878688;

	/**
	 * The singleton instance of <code>crowdcontrolproto.Qualifications</code>
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications QUALIFICATIONS = new edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord> getRecordType() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord.class;
	}

	/**
	 * The column <code>crowdcontrolproto.Qualifications.idQualifications</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord, java.lang.Integer> IDQUALIFICATIONS = createField("idQualifications", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrolproto.Qualifications.text</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>crowdcontrolproto.Qualifications.experiment_q</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord, java.lang.Integer> EXPERIMENT_Q = createField("experiment_q", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>crowdcontrolproto.Qualifications</code> table reference
	 */
	public Qualifications() {
		this("Qualifications", null);
	}

	/**
	 * Create an aliased <code>crowdcontrolproto.Qualifications</code> table reference
	 */
	public Qualifications(java.lang.String alias) {
		this(alias, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS);
	}

	private Qualifications(java.lang.String alias, org.jooq.Table<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Qualifications(java.lang.String alias, org.jooq.Table<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.ipd.kit.crowdcontrol.proto.databasemodel.Crowdcontrolproto.CROWDCONTROLPROTO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord> getPrimaryKey() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.Keys.KEY_QUALIFICATIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord>>asList(edu.ipd.kit.crowdcontrol.proto.databasemodel.Keys.KEY_QUALIFICATIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord, ?>>asList(edu.ipd.kit.crowdcontrol.proto.databasemodel.Keys.IDEXPERIMENTQUAL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications as(java.lang.String alias) {
		return new edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications rename(java.lang.String name) {
		return new edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications(name, null);
	}
}
