/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ratingoptions extends org.jooq.impl.TableImpl<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord> {

	private static final long serialVersionUID = 147782052;

	/**
	 * The singleton instance of <code>crowdcontrolproto.RatingOptions</code>
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions RATINGOPTIONS = new edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord> getRecordType() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord.class;
	}

	/**
	 * The column <code>crowdcontrolproto.RatingOptions.idRatingOptions</code>. 
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord, java.lang.Integer> IDRATINGOPTIONS = createField("idRatingOptions", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>crowdcontrolproto.RatingOptions.key</code>. 
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord, java.lang.String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>crowdcontrolproto.RatingOptions.value</code>. 
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord, java.lang.Double> VALUE = createField("value", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>crowdcontrolproto.RatingOptions.experiment</code>. 
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord, java.lang.Integer> EXPERIMENT = createField("experiment", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>crowdcontrolproto.RatingOptions</code> table reference
	 */
	public Ratingoptions() {
		super("RatingOptions", edu.ipd.kit.crowdcontrol.proto.databasemodel.Crowdcontrolproto.CROWDCONTROLPROTO);
	}

	/**
	 * Create an aliased <code>crowdcontrolproto.RatingOptions</code> table reference
	 */
	public Ratingoptions(java.lang.String alias) {
		super(alias, edu.ipd.kit.crowdcontrol.proto.databasemodel.Crowdcontrolproto.CROWDCONTROLPROTO, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions.RATINGOPTIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord> getPrimaryKey() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.Keys.KEY_RATINGOPTIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.RatingoptionsRecord>>asList(edu.ipd.kit.crowdcontrol.proto.databasemodel.Keys.KEY_RATINGOPTIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions as(java.lang.String alias) {
		return new edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Ratingoptions(alias);
	}
}
