/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tags extends org.jooq.impl.TableImpl<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord> {

	private static final long serialVersionUID = -1541940163;

	/**
	 * The singleton instance of <code>crowdcontrolproto.Tags</code>
	 */
	public static final edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags TAGS = new edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord> getRecordType() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord.class;
	}

	/**
	 * The column <code>crowdcontrolproto.Tags.idTags</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord, java.lang.Integer> IDTAGS = createField("idTags", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrolproto.Tags.tag</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord, java.lang.String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>crowdcontrolproto.Tags.experiment_t</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord, java.lang.Integer> EXPERIMENT_T = createField("experiment_t", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>crowdcontrolproto.Tags</code> table reference
	 */
	public Tags() {
		this("Tags", null);
	}

	/**
	 * Create an aliased <code>crowdcontrolproto.Tags</code> table reference
	 */
	public Tags(java.lang.String alias) {
		this(alias, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags.TAGS);
	}

	private Tags(java.lang.String alias, org.jooq.Table<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tags(java.lang.String alias, org.jooq.Table<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.ipd.kit.crowdcontrol.proto.databasemodel.Crowdcontrolproto.CROWDCONTROLPROTO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord> getPrimaryKey() {
		return edu.ipd.kit.crowdcontrol.proto.databasemodel.Keys.KEY_TAGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord>>asList(edu.ipd.kit.crowdcontrol.proto.databasemodel.Keys.KEY_TAGS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.TagsRecord, ?>>asList(edu.ipd.kit.crowdcontrol.proto.databasemodel.Keys.IDEXPERIMENTTAGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags as(java.lang.String alias) {
		return new edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags rename(java.lang.String name) {
		return new edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Tags(name, null);
	}
}
