/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.objectservice.database.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingConstraints extends org.jooq.impl.TableImpl<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord> {

	private static final long serialVersionUID = -1323055130;

	/**
	 * The singleton instance of <code>crowdcontrol.Rating_Constraints</code>
	 */
	public static final edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints RATING_CONSTRAINTS = new edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord> getRecordType() {
		return edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord.class;
	}

	/**
	 * The column <code>crowdcontrol.Rating_Constraints.id_rating_Constraints</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord, java.lang.Integer> ID_RATING_CONSTRAINTS = createField("id_rating_Constraints", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Rating_Constraints.ref_rating</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord, java.lang.Integer> REF_RATING = createField("ref_rating", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Rating_Constraints.off_constraint</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord, java.lang.Integer> OFF_CONSTRAINT = createField("off_constraint", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>crowdcontrol.Rating_Constraints</code> table reference
	 */
	public RatingConstraints() {
		this("Rating_Constraints", null);
	}

	/**
	 * Create an aliased <code>crowdcontrol.Rating_Constraints</code> table reference
	 */
	public RatingConstraints(java.lang.String alias) {
		this(alias, edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints.RATING_CONSTRAINTS);
	}

	private RatingConstraints(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord> aliased) {
		this(alias, aliased, null);
	}

	private RatingConstraints(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.kit.ipd.crowdcontrol.objectservice.database.model.Crowdcontrol.CROWDCONTROL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord> getPrimaryKey() {
		return edu.kit.ipd.crowdcontrol.objectservice.database.model.Keys.KEY_RATING_CONSTRAINTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord>>asList(edu.kit.ipd.crowdcontrol.objectservice.database.model.Keys.KEY_RATING_CONSTRAINTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingConstraintsRecord, ?>>asList(edu.kit.ipd.crowdcontrol.objectservice.database.model.Keys.REFERENCED_RATING, edu.kit.ipd.crowdcontrol.objectservice.database.model.Keys.ROFFENDED_CONSTRAINT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints as(java.lang.String alias) {
		return new edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints rename(java.lang.String name) {
		return new edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.RatingConstraints(name, null);
	}
}
