/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QualificationsDao extends org.jooq.impl.DAOImpl<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.records.QualificationsRecord, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos.Qualifications, java.lang.Integer> {

	/**
	 * Create a new QualificationsDao without any configuration
	 */
	public QualificationsDao() {
		super(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos.Qualifications.class);
	}

	/**
	 * Create a new QualificationsDao with an attached configuration
	 */
	public QualificationsDao(org.jooq.Configuration configuration) {
		super(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS, edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos.Qualifications.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos.Qualifications object) {
		return object.getIdqualifications();
	}

	/**
	 * Fetch records that have <code>idQualifications IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos.Qualifications> fetchByIdqualifications(java.lang.Integer... values) {
		return fetch(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS.IDQUALIFICATIONS, values);
	}

	/**
	 * Fetch a unique record that has <code>idQualifications = value</code>
	 */
	public edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos.Qualifications fetchOneByIdqualifications(java.lang.Integer value) {
		return fetchOne(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS.IDQUALIFICATIONS, value);
	}

	/**
	 * Fetch records that have <code>text IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos.Qualifications> fetchByText(java.lang.String... values) {
		return fetch(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS.TEXT, values);
	}

	/**
	 * Fetch records that have <code>experiment_q IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.pojos.Qualifications> fetchByExperimentQ(java.lang.Integer... values) {
		return fetch(edu.ipd.kit.crowdcontrol.proto.databasemodel.tables.Qualifications.QUALIFICATIONS.EXPERIMENT_Q, values);
	}
}
