/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pictures extends org.jooq.impl.TableImpl<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord> {

	private static final long serialVersionUID = 169917926;

	/**
	 * The singleton instance of <code>crowdcontrol.Pictures</code>
	 */
	public static final edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures PICTURES = new edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord> getRecordType() {
		return edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord.class;
	}

	/**
	 * The column <code>crowdcontrol.Pictures.idPictures</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord, java.lang.Integer> IDPICTURES = createField("idPictures", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Pictures.experiment</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord, java.lang.Integer> EXPERIMENT = createField("experiment", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>crowdcontrol.Pictures.picture_url</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord, java.lang.String> PICTURE_URL = createField("picture_url", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>crowdcontrol.Pictures.picture_license_ur</code>.
	 */
	public final org.jooq.TableField<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord, java.lang.String> PICTURE_LICENSE_UR = createField("picture_license_ur", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * Create a <code>crowdcontrol.Pictures</code> table reference
	 */
	public Pictures() {
		this("Pictures", null);
	}

	/**
	 * Create an aliased <code>crowdcontrol.Pictures</code> table reference
	 */
	public Pictures(java.lang.String alias) {
		this(alias, edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures.PICTURES);
	}

	private Pictures(java.lang.String alias, org.jooq.Table<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Pictures(java.lang.String alias, org.jooq.Table<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.ipd.kit.crowdcontrol.objectservice.databasemodel.Crowdcontrol.CROWDCONTROL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord> getPrimaryKey() {
		return edu.ipd.kit.crowdcontrol.objectservice.databasemodel.Keys.KEY_PICTURES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord>>asList(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.Keys.KEY_PICTURES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.records.PicturesRecord, ?>>asList(edu.ipd.kit.crowdcontrol.objectservice.databasemodel.Keys.EXPERIMENT_PICTURE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures as(java.lang.String alias) {
		return new edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures rename(java.lang.String name) {
		return new edu.ipd.kit.crowdcontrol.objectservice.databasemodel.tables.Pictures(name, null);
	}
}
